# [Containers]
services:
  mariadb:
    container_name: mariadb
    build: srcs/Mariadb
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - inception_network
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
  nginx:
    depends_on:
      wordpress:
        condition: service_started
    build: srcs/Nginx
    container_name: nginx
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception_network
    volumes: 
      - wordpress:/var/www/html/
    ports:
      - "443:443"
  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: srcs/Wordpress
    container_name: wordpress
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception_network
    volumes: 
      - wordpress:/var/www/html/

networks:
  inception_network:
    driver: bridge

# [volumes]
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data/wordpress
      o: bind
  