# [Containers]
services:
  mariadb:
    container_name: mariadb
    build: srcs/Mariadb
    restart: on-failure
    networks:
      - inception_network
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
  nginx:
    build: srcs/nginx
    container_name: nginx
    env_file:
      - ./.env
    restart: always
    networks:
      - inception_network
    ports:
      - "443:443"
      - "9000:9000"
networks:
  inception__network:
    driver: bridge

# [volumes]
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data
      o: bind

  