# [Containers]
services:
  mariadb:
    container_name: mariadb
    build: srcs/requirements/Mariadb
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - inception_network
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    build: srcs/requirements/Nginx
    container_name: nginx
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception_network
    volumes: 
      - wordpress:/var/www/html/
      - adminer:/usr/share/adminer/
      - static_site:/var/www/static_site/
    ports:
      - "443:443"

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: srcs/requirements/Wordpress
    container_name: wordpress
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception_network
    volumes: 
      - wordpress:/var/www/html/

# [bonus]
  redis:
    container_name: redis
    depends_on:
      - wordpress
    build: srcs/requirements/Bonus/Redis
    ports:
      - "6379:6379"
    networks:
      - inception_network
    restart: on-failure

  adminer:
    build: srcs/requirements/Bonus/Adminer
    container_name: adminer
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    volumes:
      - adminer:/usr/share/adminer/
    networks:
      - inception_network

  static_site:
    build: srcs/requirements/Bonus/Static_site
    container_name: static_site
    restart: on-failure
    networks:
      - inception_network
    ports:
      - "3000:3000"
    volumes:
      - static_site:/var/www/static_site
  
  ftp:
    container_name: Ftp
    build: srcs/requirements/Bonus/Ftp/
    networks:
      - inception_network
    ports:
      - "20:20"
      - "21:21"
      - "5000-5010:5000-5010"
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    env_file:
      - ./.env

  cadvisor:
    container_name: cadvisor
    build: srcs/requirements/Bonus/Cadvisor/
    privileged: true
    ports:
       - "8080:8080"
    networks:
     - inception_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

networks:
  inception_network:
    driver: bridge

# [volumes]
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data/wordpress
      o: bind
  adminer:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data/adminer
      o: bind
  static_site:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data/static_site
      o: bind
  