# [Containers]
services:
  mariadb:
    container_name: mariadb
    build: srcs/Mariadb
    restart: on-failure
    networks:
      - inception_network
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
  nginx:
    build: srcs/nginx
    container_name: nginx
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception_network
    ports:
      - "443:443"
      - "9000:9000"
  wordpress:
    depends_on:
      - mariadb
    build: srcs/wordpress
    container_name: wordpress
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception_network
    ports:
      - "9000:9000"
      - "3306:3306"

networks:
  inception_network:
    driver: bridge

# [volumes]
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data
      o: bind
  