# [Containers]
services:
  mariadb:
    container_name: mariadb
    build: srcs/requirements/Mariadb
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - inception_network
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    build: srcs/requirements/Nginx
    container_name: nginx
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception_network
    volumes: 
      - wordpress:/var/www/html/
      - adminer:/usr/share/adminer/
    ports:
      - "443:443"

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: srcs/requirements/Wordpress
    container_name: wordpress
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - inception_network
    volumes: 
      - wordpress:/var/www/html/

# [bonus]
  redis:
    container_name: redis
    depends_on:
      - wordpress
    build: srcs/requirements/Bonus/Redis
    ports:
      - "6379:6379"
    networks:
      - inception_network
    restart: on-failure

  adminer:
    build: srcs/requirements/Bonus/Adminer
    container_name: adminer
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    volumes:
      - adminer:/usr/share/adminer/
    networks:
      - inception_network

  static-site:
    build: srcs/requirements/Bonus/Static_site
    container_name: static-site
    restart: on-failure
    networks:
      -inception

networks:
  inception_network:
    driver: bridge

# [volumes]
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data/wordpress
      o: bind
  adminer:
    driver: local
    driver_opts:
      type: none
      device: /home/brguicho/data/adminer
      o: bind
  